---
functional:
  - Пользователь должен иметь возможность регистрироваться с помощью Email
  - Пользователь должен иметь возможность авторизовываться с помощью Email
  - Пользователь должен иметь возможность авторизовываться с помощью Github
  - Пользователь должен иметь возможность авторизовываться с помощью Discord
  - Пользователь должен иметь возможность создавать игру без авторизации
  - Пользователь должен иметь возможность создавать игру  
  - Пользователь должен иметь возможность выбирать язык программирования в игре 
  - Пользователь должен иметь возможность сдаться в игре 
  - Пользователь должен иметь возможность сбросить код до исходного шаблона
  - Пользователь должен иметь возможность проверить свое решение
  - Пользователь должен иметь возможность создавать турниры
  - Пользователь должен иметь возможность просматривать историю игр
  - Пользователь должен иметь возможность просматривать завершенные турниры 
non-functional:
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров (Edge, Firefox, Chrome, Opera)
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - Пользователь должен иметь возможность создавать игру против случайного пользователя 
  - Пользователь должен иметь возможность создавать игру против бота 
  - Пользователь должен иметь возможность выбирать сложность игры
  - Пользователь должен иметь возможность выбирать длительность игры
  - Пользователь должен иметь возможность выбирать задачу по названию или тегам
  - По истечении времени игра должна прекращаться
  - Пользователь должен иметь возможность создавать игру против друга
  - Пользователь должен иметь возможность отправлять приглашения в игру по токену
  - Пользователи должены иметь возможность отправлять сообщения в комнате игры
  - Пользователи должены иметь возможность видеть изменения кода соперника в реальном времени
  - Пользователь должен иметь возможность присоединиться к игре в лобби 
  - Пользователь должен иметь возможность просматривать игры других пользователей из лобби 
  - Пользователь должен иметь возможность отправлять сообщения другим пользователям находящимся онлайн
  - Пользователь должен иметь возможность просматривать статистикку своих игр 
  - Пользователь должен иметь возможность просматривать приглашения в игру 
  - Пользователь должен иметь возможность просматривать рейтинг пользователей 
  - Пользователь должен иметь возможность менять в настройках имя пользователя
  - Пользователь должен иметь возможность менять используемый язык программирования
  - Пользователь должен иметь возможность менять клан
  - Пользователь должен иметь возможность менять тип звука
  - Пользователь должен иметь возможность менять уровень звука 
  - Пользователь должен иметь возможность создавать задания
  - Пользователь должен иметь возможность переключать редактор кода в Vim режим
  - Пользователь должен иметь возможность вернуться к незавершенной игре 
  - Зарегистрированный с помощью Email пользователь должен иметь возможность изменить пароль в настройках